spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2020?useSSL=false
    username: root
    password: root123456
server:
  servlet:
    context-path: /pictureserver