spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pdb?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: node01
    password: 123456
  #Redis相关配置
  redis:
    database: 5
    # 配置redis的主机地址，需要修改成自己的
    host: hadoop105
    port: 6379
    password: 123456
    timeout: 5000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
        # 如果赋值为-1，则表示不限制;如果pool已经分配了maxActive个jedis实例，
        # 则此时pool 的状态为exhausted(耗尽)
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接
        # 抛出JedisConnectionException
        max-wait: 2000
#  http:
#    encoding:
#      force: true
#      charset: UTF-8
#      enabled: true

server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true
    context-path: /pictureserver
  port: 8001


mybatis:
  config-location: classpath:/mybatis.cfg.xml
  type-aliases-package: com.yan.pojo
  mapper-locations: classpath:/com/yan/mapper/*.*