spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pdb?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: node01
    password: 123456
server:
  servlet:
    context-path: /pictureserver
  port: 8001


mybatis:
  config-location: classpath:/mybatis.cfg.xml
  type-aliases-package: com.yan.pojo
  mapper-locations: classpath:/com/yan/mapper/*.*